# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: playwright

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: PlaywrigthUITests
    - name: Build
      run: dotnet build --no-restore
      working-directory: PlaywrigthUITests
    - name: PWInstall
      working-directory: PlaywrigthUITests
      run: pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
    - name: Test
      run: dotnet test PlaywrigthUITests/PlaywrigthUITests.csproj --filter "Category=SmokePW"
